- 윤년 규칙 (그레고리 력)
  1. 4의 배수일것
  2. 100의 배수면 예외
  3. 400의 배수이면 윤년

In [7]:
num = int(input("년도를 입력하세요 :"))
if((num % 4 == 0 and num%100 != 0) or num%400==0) :
  print(num, "년은 윤년입니다.")
else :
  print(num, "년은 윤년이 아닙닙니다.")

년도를 입력하세요 :2400
2400 년은 윤년입니다.

In [9]:
sum1 = 0
cnt1 = 1

while cnt1 <= 100:
  sum1 += cnt1
  cnt1 += 1

print('1~100 합 :', sum1)
print('1~100 합 :', sum(range(1,101)))
print('1~100 안에 3의 배수의 합 :', sum(range(1, 101, 3)))

1~100 합 : 5050
1~100 합 : 5050
1~100 안에 3의 배수의 합 : 1717

In [ ]:
# 시퀀스(순서가 있는) 자료형
# 문자열, 리스트, 튜플, 사전, 집합
# iterable 리턴함수 : range(), reversed(), enumerate(), filter(), map()...